# fly.toml file generated for rails-devs-demonstrator-redis on 2022-07-25T15:03:17-04:00

app = "rails-devs-demonstrator-redis"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[env]
  MAXMEMORY_POLICY="noeviction"
  APPENDONLY="yes"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
