shared:
  support: brad@fly.io
  support_mailbox: "Joe Masilotti from railsdevs <brad@fly.io>"
  notifications_mailbox: "railsdevs <brad@fly.io>"
  updates_mailbox: "railsdevs <brad@fly.io>"
  reminders_mailbox: "railsdevs <brad@fly.io>"
